### ISSUE TITLE
Handle in-toto attestation.

### ISSUE THREAD

**Issue by colek42** [testifysec/archivista#43]
Currently, Archivista only handles Witness attestation collections.  It should support any in-toto attestation.

1.  We should support in-toto attestations in DSSE envelope
2. Should we support the legacy in-toto link metadata?

**Comment by pkwiatkowski1** [comment]
Hey @colek42 checking in to see if there were any updates to supporting in-toto attestations.

**Comment by colek42** [comment]
@mikhailswift can this be closed since we have https://github.com/testifysec/archivista/pull/49 merged?
